### ISSUE TITLE
Thank you!

### ISSUE THREAD

**Issue by nicmcbride** [DouglasCAyers/sfdc-convert-notes-to-chatter-notes#13]
Hi Doug, 

First, I want to say thank you for all of the hard work that you do! 

I am trying to push this into salesforce from github and am getting this error:
Deployment CompleteTest failure, method: DeleteBatchTest.coverageAll -- System.AssertException: Assertion Failed: Expected: 0, Actual: 3 stack Class.DeleteBatchTest.coverageAll: line 29, column 1

Am I doing something to cause this? Thank you again!

**Comment by douglascayers** [comment]
Hi @nicmcbride,

Thanks for the appreciation!

Based on the error message, it seems your org has an Apex class named `DeleteBatchTest` which is failing at around line 29. You may need to review that code and make adjustments.

Unless you are wanting to customize the behavior of the notes conversion tool, try installing my managed package offering which will let you bypass the unit test issues.

At the moment, the latest version is 1.1:
* [Sandbox](https://test.salesforce.com/packaging/installPackage.apexp?p0=04tf4000000hqFk)
* [Production / Developer](https://login.salesforce.com/packaging/installPackage.apexp?p0=04tf4000000hqFk)

Thanks,

Doug
