### ISSUE TITLE
Note body is empty

### ISSUE THREAD

**Issue by kryan0618** [DouglasCAyers/sfdc-convert-notes-to-chatter-notes#19]
I have found there is an issue when the original note body is empty. The enhanced note is then created with "<p></p>" as the new note text. There are some people at our organization that created notes with only the subject.

**Comment by kryan0618** [comment]
Sorry... did not 'preview'.

The note is as follows:
![noteconversion](https://user-images.githubusercontent.com/32651743/31355464-f9045b34-acff-11e7-85d7-5e627280bcb3.png)

**Comment by douglascayers** [comment]
Thanks @kryan0618, I've got this fixed in the develop branch. Will be in the next release.

**Comment by kryan0618** [comment]
Perfect! Thanks, @DouglasCAyers !
