### ISSUE TITLE
Cannot see item in log

### ISSUE THREAD

**Issue by codebond** [DouglasCAyers/sfdc-convert-notes-to-chatter-notes#20]
Hi,
I am successfully able to convert around 94,000 notes. but for remaining 7000 notes i am not able to see them in either "Converted" or "Error" or "Skipped" related list. I am not able to trace why these 7000 notes are not getting converted.

What i have tried:
 For debugging, i have supplied 1 note id and then tried running conversion.
 Below is the debug log:

<img width="1001" alt="screen shot 2017-10-16 at 8 41 44 pm" src="https://user-images.githubusercontent.com/15388988/31641424-7f3631f2-b2b2-11e7-9bf8-ce91bd26fb5d.png">

P.S. this should have nothing to do with salesforce limits as i have already raised the limit by opening a case.

**Comment by codebond** [comment]
@DouglasCAyers Do you have any idea?

**Comment by douglascayers** [comment]
Hi @codebond,

In Salesforce Setup, please navigate to **Apex Jobs** and see if there are any reported errors for the ConvertNotesToContentNotesBatchable class.

**Comment by douglascayers** [comment]
This might be related to issue #27. The solution there was to log in as the owner of the original notes then perform the conversion. This may be related to nuanced sharing or control of the parent objects.
