### ISSUE TITLE
Invalid content ids specified

### ISSUE THREAD

**Issue by RWelc** [DouglasCAyers/sfdc-convert-notes-to-chatter-notes#27]
When running a test conversion, I get an error stating 'Invalid content ids specified: 0696100000374vW'

**Comment by douglascayers** [comment]
Hi @RWelc,

Thanks for trying out my conversion app. Could you provide some more context and screen shots around what led to this error message?

On the **Test Conversion** page, the text box lets you optionally enter one or more record ids separated by commas. If you enter a record id in the box then it must be of an object that can have attachments related to it, like an account or contact id.

The [object key prefix](https://help.salesforce.com/apex/HTViewSolution?urlname=Standard-Field-Record-ID-Prefix-Decoder&language=en_US) `069` refers to the `ContentDocument` object which is the object that Files are stored in after the attachment is converted.

Thanks

**Comment by RWelc** [comment]
Sure, thanks @DouglasCAyers.

I'm trying to convert approximately 500 legacy Notes on the Opportunity object to Enhances Notes. Running  a test on just one, however, is returning an error stating 'Invalid content ids specified: 0696100000374vW'

![image](https://user-images.githubusercontent.com/35353831/34921865-ae4027f8-f9db-11e7-98c5-564336f814a5.png)

![image](https://user-images.githubusercontent.com/35353831/34921869-b6121eb4-f9db-11e7-81c4-51e6558f532e.png)

![image](https://user-images.githubusercontent.com/35353831/34921883-13076d40-f9dc-11e7-86ca-e07a6f5829f3.png)

![image](https://user-images.githubusercontent.com/35353831/34921924-c72d4006-f9dc-11e7-9e3a-4c5799d0b17f.png)

**Comment by douglascayers** [comment]
Thank you @RWelc for the details and screen shots.

Any chance there are any other Apex triggers in the org on the `ContentDocumentLink`, `ContentDocument`, `ContentNote`, or `ContentVersion` objects?

Or any rollup helper apps rolling up counts of notes/files on parent objects?

I looked through my code again and that error message isn't something my app is generating, I've also never encountered that error before either so not sure what is causing it, which makes me think there might be other Apex code in the org interfering.

**Comment by RWelc** [comment]
Thanks @DouglasCAyers... I've looked through the org and there are no triggers or rollups on any of those objects. The org itself doesn't have many customisations, with only a handful of triggers. 

I've also tried another appexchange package, but it too is reporting exactly the same issue upon the Notes conversion. May try and get Salesforce to assist...

**Comment by douglascayers** [comment]
@RWelc did you get this resolved with Salesforce Support?

**Comment by RWelc** [comment]
Yes, thanks @DouglasCAyers. Jumped on a webex session and after troubleshooting the quick win workaround was to login as the users to perform the migration. It would only migrate user's own records.

**Comment by douglascayers** [comment]
Interesting. Glad you got it resolved. Do you mind sharing what object(s) those notes belonged to that you needed to do this for? I'm curious if there is a special standard object that caused this or maybe the OWD / sharing rules or something.

Thanks!

**Comment by RWelc** [comment]
Tbh even the salesforce techies couldn't work out what the root cause of the issue was. Executing the migration code using the Dev Console for just one note record basically narrowed down the workaround. The OWDs are public, but no sys admin users could migrate those last few problematic records. When executing the migration it would only work for the record owner when logged in as that user too. Given it was only for a handful of users I decided to bite the bullet and login as those users to complete the migration, as getting to the root cause was proving to be a bigger battle.

**Comment by douglascayers** [comment]
Very strange....

**Comment by RWelc** [comment]
Strange indeed... thanks anyway @DouglasCAyers! Happy to have done & dusted now 👍
