### ISSUE TITLE
Can't install getting an error 

### ISSUE THREAD

**Issue by ashleyleifer** [DouglasCAyers/sfdc-convert-notes-to-chatter-notes#28]
NEVER-MIND: Was installing in the wrong org, it would be great for people that work in many orgs if before you install it displays what org it's trying to install into.

I have gone through the instructions and have enabled notes in settings, and checked off Enable "Set Audit Fields upon Record Creation" and "Update Records with Inactive Owners" User Permissions, I also created a permission set to assign the to me.  I am getting this error still.... Any suggestions? 
<img width="1180" alt="screen shot 2018-01-12 at 12 55 00 pm" src="https://user-images.githubusercontent.com/8986888/34895721-ceca8c62-f79b-11e7-983f-6086a562f1f5.png">

**Comment by douglascayers** [comment]
Thanks for the update @ashleyleifer, glad you got it working!

I agree, it would be very helpful if the install package page confirmed the org being installed into. If the org has My Domain enabled then looking at the URL can sometimes help.
