### ISSUE TITLE
Unable to install in Production environment

### ISSUE THREAD

**Issue by asitu14** [DouglasCAyers/sfdc-convert-notes-to-chatter-notes#30]
Hi Doug,

I am running into this issue when trying to install the package in production.

![image](https://user-images.githubusercontent.com/34527053/35303451-d65cee30-0046-11e8-8b73-3aba735fcae5.png)

**Comment by douglascayers** [comment]
Hello @asitu14,

Please make sure you have enabled Create Audit Fields feature and granted permission to your user. 

https://github.com/DouglasCAyers/sfdc-convert-notes-to-chatter-notes#field-is-not-writeable-contentversioncreatedbyid

**Comment by asitu14** [comment]
Thanks Douglas. That fixed the issue!

**Comment by douglascayers** [comment]
Great!
