### ISSUE TITLE
Newlines being converted to <br> text

### ISSUE THREAD

**Issue by iainhack** [DouglasCAyers/sfdc-convert-notes-to-chatter-notes#35]
I'm using your excellent tool to auto-convert Notes that are being received via a Slack integration as plain text.
Unfortunately, text that contains newline characters are being converted to <br> text, and are showing up like that in the new Enhanced Note
eg 
Test message
after newline

after two newlines

Comes through in the converted Note as
Test message<br>after newline<br><br>after two newlines

Is there a specific character sequence or character I should insert into the old-style note that will be converted to a true newline in the converted note?
Thx!
iain

**Comment by iainhack** [comment]
NM - I just figured out there's an issue with my original Note creation :)

**Comment by douglascayers** [comment]
Glad you got it figured out @iainhack
