### ISSUE TITLE
Test failing - Partner Community

### ISSUE THREAD

**Issue by jennigiki** [DouglasCAyers/sfdc-convert-notes-to-chatter-notes#4]
Deployment CompleteTest failure, method: ConvertNotesToContentNotesServiceTest.test_partner_community_users -- System.QueryException: List has no rows for assignment to SObject stack Class.ConvertNotesToContentNotesServiceTest.test_partner_community_users: line 24, column 1

Hello, I'm getting the above error and have tried a number of things to resolve it, but have been unsuccessful. We have a partner community enabled in this org. Is there a quick fix to this problem?

**Comment by douglascayers** [comment]
Hi @jennigiki,

[Line 24](https://github.com/DouglasCAyers/sfdc-convert-notes-to-chatter-notes/blob/master/src/classes/ConvertNotesToContentNotesServiceTest.cls#L24) queries for standard profile named **Partner Community User**.

Please check that a partner community profile by that name exists. I've noticed that standard profile names get changed if the organization default language is not English, so may need to change the language to English for the test to pass then can change language back afterward.

Doug

**Comment by jennigiki** [comment]
Thank you, @DouglasCAyers. I added a profile with that name and did get past the error. However, there were more to follow. I will share them if you wish, but at this particular client, there are so few records (really, fewer than 20) that I'll have them "migrate" them manually. Let me know if you do want to work through the errors.

**Comment by douglascayers** [comment]
Thanks for the follow up @jennigiki.

Regarding the other errors, if you don't mind, I would be interested to know what those are. Would you please open those as new github issue(s) for investigation? I'll go ahead and close this one since solution is ensure a standard profile exists with name Partner Community User.

Thanks
